apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-wog2
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0007-tenant/tkrw-pr712-0075-0007-app/devfile-sample-wog2@sha256:f78c8cd3bc1d0e0540807ba9d6840b2e076acc6c796d6e6e993b57dfe6e7f113
        name: my-nodejs
        resources: {}
status: {}
